name: Debug FFmpeg Build

on:
  workflow_dispatch:
    inputs:
      architecture:
        description: 'Specify the architecture (e.g., armv7-a, x86, arm64-v8a). Leave blank to build all.'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone MX FFmpeg Repository
        run: git clone https://github.com/MXVideoPlayer/MX-FFmpeg.git

      - name: Patch Makefile to remove invalid references
        working-directory: MX-FFmpeg/ffmpeg/JNI/ffmpeg
        run: sed -i '/\/tests\/Makefile/d' Makefile

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential yasm nasm unzip zlib1g-dev

      - name: Prepare environment
        working-directory: MX-FFmpeg/ffmpeg/JNI
        run: |
          chmod +x rebuild-ffmpeg.sh build-ffmpeg.sh config-ffmpeg.sh

      - name: Build FFmpeg
        working-directory: MX-FFmpeg/ffmpeg/JNI
        run: |
          if [ "${{ github.event.inputs.architecture }}" == "" ]; then
            ./config-ffmpeg.sh
            ./rebuild-ffmpeg.sh
          else
            ./config-ffmpeg.sh
            ./build-ffmpeg.sh "${{ github.event.inputs.architecture }}"
          fi

      - name: Upload build logs for debugging
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: MX-FFmpeg/ffmpeg/logs/
